# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f983526c388858eaae115547c0430bf4479d3b515fc63a42ad822e6dc2b88c15de8a8b2d8bffe6ef1545e8f4385826bf4e92aaacea030812c4dce565f30d5160

test:
  secret_key_base: 2f0d42da8079166514ef14f32243e0bc900456041925cdf70927ffea43bf090ed5e0b36a649618669b4ee34818ffc0d021cea96d3307dfd039740afd0b9b4e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
